import XCTest
@testable import Yank

final class CaptureSkipTests: XCTestCase {
    func testExcludedBundleIsSkipped() {
        XCTAssertTrue(ClipboardMonitor.shouldSkip(
            frontmostBundleID: "com.example.secret",
            types: ["public.utf8-plain-text"],
            excluded: ["com.example.secret"]))
    }

    func testAutoGeneratedTypeIsSkipped() {
        XCTAssertTrue(ClipboardMonitor.shouldSkip(
            frontmostBundleID: "com.example.app",
            types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"],
            excluded: []))
    }

    func testTransientAndConcealedAreSkipped() {
        XCTAssertTrue(ClipboardMonitor.shouldSkip(
            frontmostBundleID: nil,
            types: ["org.nspasteboard.TransientType"],
            excluded: []))
        XCTAssertTrue(ClipboardMonitor.shouldSkip(
            frontmostBundleID: nil,
            types: ["org.nspasteboard.ConcealedType"],
            excluded: []))
    }

    func testNormalContentPasses() {
        XCTAssertFalse(ClipboardMonitor.shouldSkip(
            frontmostBundleID: "com.example.app",
            types: ["public.utf8-plain-text"],
            excluded: ["com.other.app"]))
    }

    func testNilBundleWithEmptyExcludedPasses() {
        XCTAssertFalse(ClipboardMonitor.shouldSkip(
            frontmostBundleID: nil,
            types: ["public.utf8-plain-text"],
            excluded: []))
    }
}
